
blank_issues_enabled: false
contact_links:
  - name: My Discord Server
    url: https://discord.gg/SKsAgCHvUm
    about: Please reach out to @sirgoodenough in one of the channels for more info. No DM's.
  - name: My Website
    url: https://www.WhatAreWeFixing.Today/
    about: Links to all the ways to interact with me, Including YouTube, FacebBook, & Follow me on Twitter...
